name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy Github Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
    - name: Deploy to CDN source station
      run: |
        echo ${{ secrets.ZEWAIL_KEY }} > ./id_rsa
        chmod ./id_rsa 400
        sh scripts/rsa.sh
        sh scripts/transport.sh